### PR TITLE
cross platfom changes

### PR DESCRIPTION
**Pull request by Fydon**
This enables the compiling phase on `create-env` to work on Windows (discussed within #278), although not using Windows Subsystems for Linux. Tested using the bash that comes with [git for windows][1].

[1]: https://git-for-windows.github.io/

### CODE REVIEW

**Comment by Fydon** [comment]
Sorry I just realised that I was running `create-env` against an earlier build. Although all the tests pass on Windows and Linux, this is missing a part of the changes required for compilation to work. I'll rather open a new pull request when I've worked more on this.

**Comment by Fydon** [comment]
All the tests pass on Linux and the tests that I've changed or added pass on Windows. With these changes I'm able to compile `bosh-virtualbox-cpi` on Windows.

**Comment by Fydon** [comment]
Currently compiling in bosh-cli [relies on bash being able to run it][1]. Packaging scripts are called during compilation, but packaging scripts can now also be [Powershell scrips][2]. Do these Powershell packaging scripts also run in bash on Linux?

Windows relies on the file extension to know what should be used to execute the file. 

This pull request now also requires [all CPI scripts to be executable by bash][3] as well.

For this pull request to work, bash needs to be in Windows's PATH environment variable. This won't work with Windows Subsystems for Linux. For Windows Subsystems for Linux to work each environment variable need to be added to the bash environment, e.g. [by exporting each inside the call][4].

[1]: https://github.com/cloudfoundry/bosh-cli/blob/master/installation/pkg/compiler.go#L96
[2]: https://github.com/bosh-packages/golang-release/blob/master/packages/golang-1.8-windows/packaging
[3]: https://github.com/Fydon/bosh-cli/blob/7c34d84f92a161668f56477227c767e23d5dbbd8/cloud/cpi_cmd_runner.go#L104
[4]: https://github.com/Fydon/bosh-cli/blob/feature/CompileOnWindows/installation/pkg/compiler.go#L106-L117

**Comment by jaresty** [comment]
merge story [#152973930](https://www.pivotaltracker.com/story/show/152973930)

**Comment by jfmyers9** [comment]
Closing this due to inactivity.

If you would like to discuss this contribution further, please open a new issue.

**Pull request closed without merging**
