### PR TITLE
WIP: Adds more informative errors on SSL validation failure

### PR DESCRIPTION
**Pull request by ljfranklin**
- Shows more human-readable errors messages with better calls to action
- TODO: add tests
- TODO: don't change files in vendor, submit separate PR to bosh-utils

### CODE REVIEW

**Comment by ljfranklin** [comment]
## Example SSL Errors

#### Forgetting to use `--ca-cert` flag when Director has self-signed cert

```bash
$ bosh log-in -e 10.85.57.6
Fetching info:
  Performing request GET 'https://10.85.57.6:25555/info':
    Performing GET request: Get https://10.85.57.6:25555/info: x509: certificate signed by unknown authority:
      The Director's SSL Certificate is signed by an unknown Certificate Authority (CA). Please specify the CA Certificate with the `--ca-cert` flag or configure your director with signed certificates: http://bosh.io/docs/director-certs.html#configure.

Exit code 1
exit status 1
```

#### Specifying an IP address when Cert is only valid for DNS Hostnames

```bash
$ bosh log-in -e 104.197.154.53
Fetching info:
  Performing request GET 'https://104.197.154.53:25555/info':
    Performing GET request: Get https://104.197.154.53:25555/info: x509: cannot validate certificate for 104.197.154.53 because it doesn't contain any IP SANs:
      The Director's SSL Certificate is not valid for the IP address you specified. Please specify the DNS Hostname instead of the IP with the `env` command or the `--environment` flag.

Exit code 1
exit status 1
```

#### Specifying a Hostname that is not covered by the Cert

```bash
$ bosh log-in -e local-bosh
Fetching info:
  Performing request GET 'https://local-bosh:25555/info':
    Performing GET request: Get https://local-bosh:25555/info: x509: certificate is valid for 10.85.57.6, not local-bosh:
      The Director's SSL Certificate did not match the hostname you specified. Please specify a valid hostname or an IP address with the `env` command or the `--environment` flag.

Exit code 1
exit status 1
```

**Comment by ljfranklin** [comment]
Quick notes from @cppforlife:

- the flag names probably don't belong in the `director` package as that package might used as a library, not only as a CLI
- try to remove duplication so we don't have to add checks on every GET, POST, etc.

**Comment by cppforlife** [comment]
also error checking should apply to `uaa` library as well.

**Comment by cppforlife** [comment]
would be nice as well to cover:
- dns errors (might not be correct name)
- connection timeout errors (state that connectivity might be blocked)

**Comment by ljfranklin** [comment]
Going to close this out as it's gone pretty stale now and I'm probably not going to finish it. Still would be nice to have better SSL errors though : )

**Comment by drnic** [comment]
Nice.

**Pull request closed without merging**
