### PR TITLE
Config server integration

### PR DESCRIPTION
**Pull request by cppforlife**
Following PR provides two features:

- storing deployment state and variables in config server API compatible backend (connectable via --config-server-* flags) by specifying `config-server://` schema for --state and --vars-store flags

```
bosh create-env ~/workspace/bosh-deployment/bosh.yml \
  --state config-server://state.json \
  --vars-store config-server://creds.yml \
  -o ~/workspace/bosh-deployment/virtualbox/cpi.yml \
  -o ~/workspace/bosh-deployment/virtualbox/outbound-network.yml \
  -o ~/workspace/bosh-deployment/jumpbox-user.yml \
  -o ~/workspace/bosh-deployment/uaa.yml \
  -o ~/workspace/bosh-deployment/credhub.yml \
  -v director_name=vbox2 \
  -v internal_cidr=192.168.50.1/24 \
  -v internal_gw=192.168.50.1 \
  -v internal_ip=192.168.50.8 \
  -v outbound_network_name=NatNetwork \
  --config-server-url=https://192.168.50.6:8844 \
  --config-server-namespace=vbox2 \
  --config-server-tls-ca=<(bosh int credhub/creds.yml --path /credhub_tls/ca;bosh int credhub/creds.yml --path /default_ca/certificate) \
  --config-server-uaa-url=https://192.168.50.6:8443 \
  --config-server-uaa-client=credhub-admin \
  --config-server-uaa-client-secret=`bosh int credhub/creds.yml --path /credhub_admin_client_secret` 
```

- storing deployment state and variables in memory to aid deploying of "throw away" instances such as jumpboxes. example below just uses memory for vars store. variables that are generated for the deployment are stored in memory while command is running and are thrown away at the end.

```
bosh create-env ~/workspace/jumpbox-deployment/jumpbox.yml \
  --state ./state.json \
  --vars-store memory://creds.yml \
  -o ~/workspace/jumpbox-deployment/virtualbox/cpi.yml \
  -o ~/workspace/jumpbox-deployment/virtualbox/outbound-network.yml \
  -v internal_cidr=192.168.50.1/24 \
  -v internal_gw=192.168.50.1 \
  -v internal_ip=192.168.50.8 \
  -v outbound_network_name=NatNetwork \
  --var-file private_key=<(lastpass --note "jumpbox-private-key")
```

### CODE REVIEW

**Comment by genevieve** [comment]
Would it be possible to add environment variables for the config server flags such that bbl could set those vars for the user and the user can execute `bosh create-env` with fewer cli flags?

**Comment by cppforlife** [comment]
+1 on env vars, will add.

**Comment by coreyti** [comment]
Hey BOSH folk. Just wanted to add a note to indicate **strong** interest in this functionality. At the moment, we have a bespoke script in our pipeline to pull variables with a particular prefix out of our Concourse CredHub, write those to a variables file, and create-env using that. As you can imagine, we are not happy with that approach.

**Comment by jfmyers9** [comment]
Closing and reopening to generate a tracker story.

**Pull request closed without merging**
