### PR TITLE
Show colored diff in stdout during bosh deploy steps

### PR DESCRIPTION
**Pull request by aemengo**
screen shot 2017-10-14 at 10 03 43 am

Was originally present in the v1 cli

### CODE REVIEW

**Comment by dpb587-pivotal** [comment]
Hi - thanks for taking a look at this! I think we'll need to consider a slightly different approach though. Rather than attempting to add methods for very specific use cases of add/remove lines, we probably need to plan out a way for generic coloring support which may involve some of the vendor'd libraries as well. That will require a bit more planning.

The coloring looks nice and has been mentioned on slack, too, but is it more for visual convenience or do you have another use case?

**Comment by aemengo** [comment]
@dpb587-pivotal Thanks for getting back to me on this. This is more for visual convenience.

**Comment by jaresty** [comment]
merge story [#152973883](https://www.pivotaltracker.com/story/show/152973883)

**Comment by jfmyers9** [comment]
Closing this due to inactivity.

If you would like to discuss this contribution further, please open a new issue.

**Pull request closed without merging**
