### PR TITLE
If the release is an invalid URL, error includes URL

### PR DESCRIPTION
**Pull request by cunnie**
It would have saved me about 1 hour this morning if the error message had included the URL. Really. Don't ask.

Ran unit tests. Did not run integration or acceptance tests.

### CODE REVIEW

**Comment by dpb587-pivotal** [comment]
But... I want to ask. Off by one when reviewing the error message?

**Comment by cppforlife** [comment]
@cunnie I m a bit concerned that it would print potentially some basic auth password, etc.

**Comment by cunnie** [comment]
@cppforlife : Good point — we've gone to a lot of trouble to not leak passwords, and this would be a step backwards. Let me see if I can first redact any passwords from the URL before I print.

@dpb587 : I'm not sure what you mean by off-by-one, but what led up to this error was that I _specified the wrong manifest on the command-line_: e.g. `bosh create-env wrong-manifest.yml`

**Comment by cunnie** [comment]
I'm closing this PR — if I have time to modify this PR to redact sensitive information, I'll open a new PR.

**Pull request closed without merging**
