### PR TITLE
Move cmd/opts.go and related files to cmd/opts subdirectory

### PR DESCRIPTION
**Pull request by xtreme-conor-nosal**
The `cmd` package contains many files related to flag parsing (Opts, Args, etc). This PR moves these classes into a new `cmd/opts` package, adds a suite_test.go, and updates the imports/usage of the classes.

This change allows downstream projects to import `cmd/opts` for use with passthrough flags, which currently can't be done without importing the entire project.

### CODE REVIEW

**Comment by xtreme-conor-nosal** [comment]
Closing for CLA

**Comment by aashah** [comment]
Hey @xtreme-conor-nosal, thanks for the PR

Just curious what type of project you're building on top of the `cmd/opts/` of the bosh-cli. The change is harmless, and we have no reservations beyond this curiosity.

Thanks,
Aakash

**Comment by xtreme-conor-nosal** [comment]
Hi @aashah,

I'm building a CLI that aims to organize collections of bosh ops files into reusable 'scenarios', which are stored in another yml file. To offer flexibility for one-off deployments, the tool uses the double-dash syntax to allow passthrough flags (e.g. `my-tool -myflag -- -v boshvar -o some-ops-file`).

Rather than duplicate the flag parsing for `bosh interpolate`, I would like to import cmd/opts and use the InterpolateOpts directly (along with bosh's fork of go-flags and the director/template classes).

**Comment by luan** [comment]
@xtreme-conor-nosal do you mind fixing the conflicts so we can merge? Sorry we dropped the ball when it was clean :)

**Comment by xtreme-conor-nosal** [comment]
@luan done :)

**Pull request merged**
