### PR TITLE
add inspect-stemcell-tarball command

### PR DESCRIPTION
**Pull request by kcboyle**
We've added a command to make stemcell metadata available through the CLI.

The intent is to help automators working around bosh move on from getting information about a stemcell by parsing its filename.

Please note that this also contains breaking changes to the director package, as the FSArchiveWithMetadata interface has been replaced as an abstraction by FSReleaseArchive and FSStemcellArchive, and the Info() method associated with these now returns an artifact-specific (exported) struct rather than using multiple return values to represent name and version.

We discussed the breaking changes to the director package's interface with the bosh time before choosing the route we took in this PR.

Signed-off by @anEXPer

### CODE REVIEW

**Comment by jtarchie** [comment]
We split out the fake updates.

As for the command name, we just went with what @cppforlife suggested back in our tracker story: https://www.pivotaltracker.com/story/show/157849190

We'd be fine with alternate words in the command name.

There's not a lot in common with `inspect-release` or a theoretical `inspect-stemcell` in terms of interface or implementation. We prefer them as separate commands.

Signed-off by @anEXPer

**Comment by kcboyle** [comment]
@jfmyers9 is there anything else you need from our end? we just committed a fix due to a merge conflict in develop. Happy to contribute/go back. Just let us know

**Comment by jfmyers9** [comment]
Sorry for the slow response. We are still having internal communications about the name of the command. We will definitely have a response early next week, and hopefully get the chance to prioritize a review sooner rather than later.

**Comment by jfmyers9** [comment]
Hey @kcboyle,

We decided that we didn't like leaking `tarball` into the name of the command. Is there any chance you could change the name of the command to `inspect-local-stemcell`? Other than that, this PR looks good for us to merge.

Best,

@jfmyers9

**Comment by fredwangwang** [comment]
@jfmyers9 the command name has been changed to `inspect-local-stemcell`. Let us know if there is anything else you need from our end.

**Comment by jfmyers9** [comment]
Thanks! We have prioritized the tracker story and will hopefully get a pair merging it sometime this week.

**Comment by pivotal-mp** [comment]
Thanks for the PR! We merged in [this commit](https://github.com/cloudfoundry/bosh-cli/commit/488291bcdb3ee95d4d9b2aa7a9783003efb8230c). 
Github seems to not be automatically recognizing the merge since we had to manually fix a rebase conflict. Sorry about the Github troubles, it looks like we have to close this PR manually since the commits have been merged.

**Pull request closed without merging**
